homepage:
    pattern:  /
    defaults: { _controller: RedwoodWebBundle:Default:index }

register:
    pattern:  /register
    defaults: { _controller: RedwoodWebBundle:Register:index }

login:
    pattern:  /login
    defaults: { _controller: RedwoodWebBundle:Login:index }

login_check:
    pattern:  /login_check

logout:
    pattern:  /logout

register_success:
    pattern:  /register/success/{id}/{hash}
    defaults: { _controller:  RedwoodWebBundle:Register:success }

register_email_verify:
    pattern:  /register/email/verify/{token}
    defaults: { _controller: RedwoodWebBundle:Register:emailVerify }

password_reset:
    pattern:  /password/reset
    defaults: { _controller: RedwoodWebBundle:PasswordReset:index }

password_reset_update:
    pattern:  /password/reset/update
    defaults: { _controller: RedwoodWebBundle:PasswordReset:update }

note_inbox_show:
    pattern:  /inbox
    defaults: { _controller: RedwoodWebBundle:Note:inboxShow }